@startuml

ExperimentManager *-->DocumentCrawler
ExperimentManager *-->InterpretationManager
ExperimentManager *-->ResultEvaluator
DocumentCrawler-->DocSet
DocSet *-- Doc
Doc .. DocumentFILE
InterpretationManager *--> SubjectsCreator
SubjectsCreator *-->Subject
Subject -->Interpretation
Subject ..>DocSet
Subject*--KnowledgeGraph
InterpretationManager-->RequirementsDocument
RequirementsDocument *-- Requirement
Interpretation ..>Requirement
InterpretationManager-->Distance
ResultEvaluator-->Distance
ResultEvaluator-->AutoAmbiguityResult
ResultEvaluator-->Evaluation
ResultEvaluator-->ManualAmbiguityResult
Distance .. DistancesFILE
ResultEvaluator .. DistancesFILE


@enduml